package main

import (
    "crypto/aes"
    "crypto/cipher"
    "crypto/rand"
    //"encoding/binary"
    "errors"
    "io"
    "fmt"
    "strings"
    "time"
)

var key []byte = []byte{
    0x2b, 0x7e, 0x15, 0x16,
    0x28, 0xae, 0xd2, 0xa6,
    0xab, 0xf7, 0x15, 0x88,
    0x09, 0xcf, 0x4f, 0x3c,
}

var (
	cliMessageChan = make(chan string, 10)
	command string = ""
	pendingCommand string =""
	echo_to_stdout string = "off"
	store_command int = 0
	chunkStartCheck string = "true"
	decoded_cmd_byte []byte
	fifo4 []byte = []byte("0000")
)

func encrypt(key, plaintext []byte) (string, error) { //generated by AI
    block, err := aes.NewCipher(key)
    if err != nil {
        fmt.Println("aesNewCipher err -", err)
        return "", err
    }
    gcm, err := cipher.NewGCM(block)
    if err != nil {
        fmt.Println("newGcm err -", err)
        return "", err
    }

    nonce := make([]byte, gcm.NonceSize()) // 12 bytes
    if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
        fmt.Println("Nonce Read err -", err)
        return "", err
    }

    // Seal(dst, nonce, plaintext, additionalData)
    // prepends nonce to the output so you get: nonce || ciphertext || tag
    return string(gcm.Seal(nonce, nonce, plaintext, nil)), nil
}

func decrypt(key, ciphertext []byte) (string, error) { //generated by AI
    block, err := aes.NewCipher(key)
    if err != nil {
        fmt.Println("aesNewCipher 2 err -", err)
        return "", err
    }
    gcm, err := cipher.NewGCM(block)
    if err != nil {
        fmt.Println("newGcm2 err -", err)
        return "", err
    }

    nonceSize := gcm.NonceSize()
    if len(ciphertext) < nonceSize+gcm.Overhead() {
        fmt.Println("Detected ciphertext too small")
        return "", errors.New("ciphertext too short")
    }

    nonce, ct := ciphertext[:nonceSize], ciphertext[nonceSize:]
    pt, err := gcm.Open(nil, nonce, ct, nil)
    return string(pt), err
}

func decoderEngine(buf []byte) (string, string){

	var current_decoded_byte byte
	cmd_bitIndex :=0 
	//var fifo4 []byte
	var finalCommand string = ""
	var isFullMessage string = "false"
	
	if chunkStartCheck=="true"{
		fifo4 = fifo4[:0]
		decoded_cmd_byte = decoded_cmd_byte[:0] //no pending STOP message
		for _, stegd_byte := range(buf[:8*4]){ //if server has a command to send, the first 4 bytes would be STRT, unless it is a big command
			lsb := stegd_byte & 1
			current_decoded_byte = (current_decoded_byte << 1) | lsb
			cmd_bitIndex++
			if cmd_bitIndex==8{
				fifo4 = append(fifo4, current_decoded_byte)
				cmd_bitIndex =0
			}
		}

		if "STRT"==string(fifo4){
			chunkStartCheck="false" 	//big commands will be taken care, by not performing this chek, until a STOP is encountered
		}else{
			return  "", "none"//dont bother decoding rest of the chunk
		}
	}
	//fifo4 = fifo4[:0]
	
	for _, stegd_byte := range(buf[:len(buf)]){
		lsb := stegd_byte & 1
		current_decoded_byte = (current_decoded_byte << 1) | lsb

		cmd_bitIndex++
		if cmd_bitIndex==8{
			if store_command==1{
				decoded_cmd_byte = append(decoded_cmd_byte, current_decoded_byte)
			}
			fifo4 = append(fifo4, current_decoded_byte)

			if len(fifo4) > 4{
				fifo4 = fifo4[1:]
			}
			//fmt.Println("fifo4 state ", string(fifo4))
			if "STRT"==string(fifo4){
				store_command = 1
				isFullMessage = "false"
			}
			if "STOP"==string(fifo4){
				isFullMessage = "true"
				store_command = 0
				chunkStartCheck = "true"
				fifo4 = fifo4[:0]
				//fmt.Println("Pre decryptio = ", decoded_cmd_byte)
				finalCommand = strings.Replace(string(decoded_cmd_byte), "STOP", "", -1)

				finalCommand , err:= decrypt(key, []byte(finalCommand))
				//if  echo_to_stdout=="true"{fmt.Println("decrypted cmd - ", finalCommand)}
				
				if err!=nil{
					fmt.Println("Client decrypt error -", err)
					return "echo 'decr err'", "decrErr"
				}
				decoded_cmd_byte = decoded_cmd_byte[:0]
				//fmt.Println("$>", finalCommand)
				return finalCommand, isFullMessage
			}
			//fmt.Println("Debug info, fifo4 status - ", string(fifo4))
			cmd_bitIndex =0
			current_decoded_byte = 0
		}
		//fmt.Println("Recieved ", n, " bits with value", string(buf[:n]), "and bytes ", buf[:n])
	}
	return finalCommand, isFullMessage
}

func encodingEngine(chunk []byte, ChunkSize int) ([]byte){

	cmd_len_threshold := ChunkSize/8
	var err error

	select {
	case cmd := <-cliMessageChan:
		command = cmd
		if len(command) > 0 {
			command, err = encrypt(key, []byte(command))
			if err!=nil{
				fmt.Println("Encryption errored out -", err)
			}
			command = "STRT"+command+"STOP"
			//fmt.Println("Enrypted command =", []byte(command))
		}
		
		if len(pendingCommand)>0{
			command = pendingCommand[:min(len(pendingCommand), cmd_len_threshold)]+command
			pendingCommand = pendingCommand[min(len(pendingCommand), cmd_len_threshold):]
		}
		if len(command)>cmd_len_threshold{
			pendingCommand += command[cmd_len_threshold:]
			command = command[:cmd_len_threshold]
		}

	default:
		if len(pendingCommand)>0{
			command = pendingCommand[:min(len(pendingCommand), cmd_len_threshold)]+command
			pendingCommand = pendingCommand[min(len(pendingCommand), cmd_len_threshold):]					
			//fmt.Printf("Injecting payload (%d characters)...\n", len(command)+8)
			goto label1
			//ensures pending msg gets sent, when there's no cli message but there's pending msg
		}

		//dont go through the whole thing of encoding, if we dont have any message to be sent.
		return chunk[:ChunkSize]
	}
label1 :
	commandBytes := []byte(command) //we use this, so go doesnt increase rune size on seeing probable non-utf8 chars in ciphertext
	
	//----code to inject LSB from cmd_bitstring array into audio stream.
	if echo_to_stdout=="on"{
		fmt.Println("Chunk length = ", len(chunk))
		fmt.Printf("Injecting payload (%d characters)...\n", len(command))
	}

	cmd_bitIndex :=0
	cmd_charIndex :=0
	var audio_stegd_bytes []byte
	for _, aud_byte := range chunk{
		if cmd_charIndex == len(commandBytes) {
			if echo_to_stdout=="on"{
				fmt.Println("stegged bs length ",len(audio_stegd_bytes), "\nstegged bs ", audio_stegd_bytes)
			}
			break
		}

		ival := (commandBytes[cmd_charIndex] >> (7 - uint(cmd_bitIndex))) & 1 //bitShift bit extraction
		aud_byte = (aud_byte & 0xFE) | ival

		audio_stegd_bytes= append(audio_stegd_bytes, aud_byte)
		//fmt.Println("cmd_bitstring at ", cmd_charIndex, "=", string(byte(cmd_bitstring[cmd_charIndex])))

		cmd_bitIndex++
		if cmd_bitIndex==8{
			cmd_charIndex ++
			cmd_bitIndex =0
		}

	}
	//fmt.Println("command encode successful")

	//*********-------------------end------------------*****************//
	copy(chunk[:cmd_charIndex*8], audio_stegd_bytes[:cmd_charIndex*8])

	if echo_to_stdout == "on"{
		fmt.Println("Log - ",time.Now()," Request recieved and Replied to ", "443")
	}
	return (chunk[:ChunkSize])
}